### ISSUE TITLE
mzTab version number 1.1 or 2.0??

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#129]
Seems rather trivial but while drafting the manuscript it struck me as odd that we're describing mzTab-M as version 1.1 implying it is pretty similar to version 1.0, when in reality it is rather different. 

Can we have votes (also from proteomics people) as to whether we shift the versioning now to make the new version 2.0, to make it clear that it is rather subtantially changed from version 1.0? 

When it comes to the proteomics part, the changes probably won't be that subtantial, but I for one would vote for doing away with the distinctions of Complete vs Summary and Ident vs Quant, (same as for metabolomics), so this would seem like a major version increment.

**Comment by ypriverol** [comment]
@andrewrobertjones My suggestion is to do not mention in the manuscript title or highlight in the manuscript the versioning problem (only mention it) like we normally have done before in the past with mzIdentML papers. **We should introduce mzTab-M which is the new concept**. 

For the PSI-MS document process, I will vote to increase as you said to 2.0 because (I agree with you), this is a major change in the file format.

**Comment by javizca** [comment]
I would also vote for 2.0. I think it would be "cleaner". And also it fits well with the PSI convention (no backwards compatibility)

**Comment by hartler** [comment]
I would also vote for 2.0, since mzTab-M is substantially different from version 1.0.

**Comment by rsalek** [comment]
Same here version 2.0 makes sense and sounds better!
