### ISSUE TITLE
Use of compact URI

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#172]
Philippe flagged up a question on the manuscript recorded here: 

Does it mean identifiers should only be reported using ‘compact URI’ specification - https://www.w3.org/TR/2010/NOTE-curie-20101216/

"In a row of the final results (SML table), the export software can include one or more identifiers from external databases, using a system such as “CHEBI:16811” "

**Comment by nilshoffmann** [comment]
@andrewrobertjones @proccaserra
The prefix for the external resource has to be registered in the Metadata section's database element:

`
...
MTD database[1] [MIRIAM, MIR:00100079, HMDB, ]
MTD database[1]-prefix hmdb
MTD database[1]-version 3.6
MTD database[1]-uri http://www.hmdb.ca/
...
`
Here, a link is established via the -uri property and the -prefix property. Together with the native database identifier, e.g. following <PREFIX:NATIVE_ID>: HMDB:HMDB0001847 the result is pretty much a CURIE compatible entry. However, since we also allow "local" user-defined databases with a custom prefix and no uri, the IDs are not purely Curie compatible. That is why we have this indirection in place.

If there is however an authoritative resource like identifiers.org, one can directly resolve the database identifiers.

**Comment by nilshoffmann** [comment]
We principally have two ways in place: the local database definition in the metadata section and the uri for small molecules in the SML table. The latter one needs to be a proper URI, i.e. to identifiers.org.

https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/2_0-Metabolomics-Draft/mzTab_format_specification_2_0-M_draft.adoc#638-uri
