### ISSUE TITLE
StudyVariable vs assay as mandatory (formerly issue called: consider if assay only reports are allowed)

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#29]
mandatory reporting of study_variable columns prior to statistical downstream processing might not fit well to data processing workflows.
Maybe relaxing the requirement of summary files to be also able to report assays only yields cleaner files. Otherwise, assay information needs to be represented in study_variables columns that might not match to actual study_variables (call it a hack).

**Comment by mwalzer** [comment]
I think scenario _T2. Export of results to external software_ and "..is also intended to provide local LIMS systems as well as MS proteomics repositories a simple way to share and combine basic information" from the specification document almost describes a usecase of mzTab to transport information into statistical software to produce study_variable column content in the first place. I am all for it.

**Comment by andrewrobertjones** [comment]
Changed name of the issue, since there is a wider discussion point here. 

In 1.0 Summary files, the focus was on giving SV values as the "final" output of the experiment, and assay values should be given in Complete files (optional in Summary files). However, I'm struggling to come up with a use case where the file consumer wouldn't want the assay-level values. 

**Point 1 - SV or assays mandatory?**
The SV values are trivial to recalculate anyway, so I would vote for changing the balance that assay values are always mandatory but SV level values are optional. Current metabolomics1.1 draft has SV quant at nullable=true.

**Point 2 - Should SVs be generally mandatory e.g. in metadata**

Case for: Forces exporters to report these. For "final" data, seems kind of important to know experimental groupings, otherwise data is largely uninterpretable.

Case against: Software may not know SVs at all or at that point in the workflow. 

My vote would be to leave SVs are mandatory, but come up with hacks for internal pipelines e.g. having a single SV over all assays, or having SVs referencing no assays.


**Point 3**
2 - Data about SVs**

1.0 specs suggest to report st_dev and st_error. It is almost always more meaningful to have coefficient of variation reported here (st_dev / mean), since this normalises for the size of the mean.

**Comment by jmrein** [comment]
I can see having SVs with no assays being a source of confusion and bugs, but simply reporting a single SV covering all assays seems a reasonable way of covering the "SVs are not relevant at this point in my internal pipeline" while _encouraging_ people to specify SVs if at all possible.

**Comment by andrewrobertjones** [comment]
Closing this issue. It has been resolved for mzTab-M 1.1 - studyvariables and assay are both mandatory. There is no distinction between Complete vs Summary any more. 

Discussion will need to be re-opened in the future for proteomics
