### ISSUE TITLE
Example in charge column: add for negative polarity

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#78]
To reduce potential ambiguities in reporting, we should add an example for negative charge, e.g., that it is specified by -1

**Comment by nilshoffmann** [comment]
Take from Lipidomics example.

**Comment by timosachsenberg** [comment]
I can add the example but can you link to the file?

**Comment by nilshoffmann** [comment]
https://github.com/nilshoffmann/jmzTab-m/blob/master/io/src/test/resources/metabolomics/lipidomics-example.mzTab

COM	Evidence rows for parent / fragment ions.																				
COM	Primary use case: report single hits from spectral library or accurate mass searches without quantification. -> Qualification																				
SEH	SME_ID	evidence_unique_ID	database_identifier	chemical_formula	smiles	inchi	chemical_name	uri	derivatized_form	adduct_ion	exp_mass_to_charge	charge	theoretical_mass_to_charge	opt_global_mass_error	spectra_ref	identification_method	ms_level	id_confidence_measure[1]	rank	opt_global_qualifiers_evidence_grouping_ID_REFS	opt_global_scan_polarity
SME 1 1 LM:LMSP0501AB02 C42H83NO3 CCCCCCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CO)[C@H](O)/C=C/CCCCCCCCCCCCC InChI=1S/C42H83NO3/c1-3-5-7-9-11-13-15-17-18-19-20-21-22-23-24-26-28-30-32-34-36-38-42(46)43-40(39-44)41(45)37-35-33-31-29-27-25-16-14-12-10-8-6-4-2/h35,37,40-41,44-45H,3-34,36,38-39H2,1-2H3,(H,43,46)/b37-35+/t40-,41+/m0/s1 LacCer d18:1/12:0 | C12 lactosyl ceramide | N-(dodecanoyl)-1-b-lactosyl-sphing-4-enine http://www.lipidmaps.org/data/LMSDRecord.php?LM_ID=LMSP02010012 null [M+H]1+ 650.6432 1 650.6446 -2.1517 ms_run[1]:index=731 [,, qualifier ions exact mass,] [MS,MS:100511, ms level, 1] 0.958 1 2 [MS, MS:1000130, positive scan, ]

**Comment by timosachsenberg** [comment]
Thanks Nils. 
In the the light of having only one file per polarity, it would imho make more sense to annotate this in the meta data section.
What is your take on this. See also https://github.com/HUPO-PSI/mzTab/issues/56 ?

**Comment by nilshoffmann** [comment]
In Lipidomics, we definitely have the use case that an identification is based on positive and negative mode evidence. But that may be something to write out in a "dialect" since that would also involve having one file for the negative mode results, one for the positive mode, and possibly one as defined with this example to be able to combine those. 

AFAIK, some MSs can switch between positive and negative mode within one run, but that is usually not done at least in our lab, since the switching may take some ms, thus leading to potential loss of acquisition windows for other ions during switching.

To keep the format simple, we could state, that we recommend to set the polarity in the metadata section globally (as in #56) or on evidence / scan level as an optional CV column. I would personally not require to set it on ms_run, since there may be mixed files where we would need to define an exception / special case for.

**Comment by timosachsenberg** [comment]
Putting it in the metadata sounds sensible. Though, I think we still miss a negative mode example (e.g. to show how **charge** column and **adduct**  column would look like. Maybe then we would not even need an extra scan polarity column? Sorry for these basic questions... my background is more on the proteomics part.

**Comment by andrewrobertjones** [comment]
We put negative integer examples in the specs

**Comment by andrewrobertjones** [comment]
Re-opening - Thermo raw use positive ints and positive m/z but flag that this is a negative scan. This probably gets carried through to mzML on conversion

**Comment by timosachsenberg** [comment]
Yes, I think we query this flag in our accuratemasssearch tool.
